# # name: Build and Deploy to Kubernetes -d

# # on:
# #   push:
# #     branches:
# #       - main

# # jobs:
# #   deploy:
# #     runs-on: ubuntu-latest

# #     steps:
# #       - name: Checkout repository
# #         uses: actions/checkout@v3

# #       - name: Set up Node.js 18.17.0
# #         uses: actions/setup-node@v4
# #         with:
# #           node-version: 18.17.0

# #       - name: Set up Python 3.11
# #         uses: actions/setup-python@v5
# #         with:
# #           python-version: 3.11

# #       - name: Install Python dependencies
# #         run: |
# #           python -m pip install --upgrade pip
# #           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

# #       - name: Install Node.js dependencies and optionally build UI
# #         working-directory: ui/litellm-dashboard
# #         run: |
# #           npm install
# #           # if npm pkg get scripts.build | grep -vq 'null'; then
# #           # echo "Running npm run build..."
# #           # npm run build
# #           #  else
# #           #     echo "No build script found. Skipping build."
# #           #   fi
# #       # - name: Install Node.js dependencies and optionally build UI
# #       #   working-directory: ui/litellm-dashboard
# #       #   run: |
# #       #     npm install
# #       #     if npm run | grep -q 'build'; then
# #       #       echo "Running npm run build..."
# #       #       npm run build
# #       #     else
# #       #       echo "No build script found. Skipping build."
# #       #     fi

# #       - name: Log in to Docker Hub
# #         uses: docker/login-action@v2
# #         with:
# #           username: ${{ secrets.USER_NAME_DOCKER }}
# #           password: ${{ secrets.PASSWORD_DOCKER }}

# #       - name: Build Docker image
# #         run: docker build -t ${{ secrets.USER_NAME_DOCKER }}/llm:latest1 .

# #       - name: Push Docker image to Docker Hub
# #         run: docker push ${{ secrets.USER_NAME_DOCKER }}/llm:latest1
# # name: Build and Deploy

# # on:
# #   push:
# #     branches:
# #       - main  # Change to your deployment branch if needed

# # jobs:
# #   deploy:
# #     runs-on: ubuntu-latest

# #     steps:
# #       - name: Checkout repository
# #         uses: actions/checkout@v3

# #       # Set up Node.js 18.17.0
# #       - name: Set up Node.js 18.17.0
# #         uses: actions/setup-node@v4
# #         with:
# #           node-version: 18.17.0

# #       # Set up Python 3.11 (if you have Python dependencies)
# #       - name: Set up Python 3.11
# #         uses: actions/setup-python@v5
# #         with:
# #           python-version: 3.11

# #       # Install Python dependencies if any
# #       - name: Install Python dependencies
# #         run: |
# #           python -m pip install --upgrade pip
# #           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

# #       # Install Node.js dependencies and build the UI (React/Vue app)
# #       - name: Install Node.js dependencies and build UI
# #         working-directory: ui/litellm-dashboard
# #         run: |
# #           npm install
# #           npm run build

# #       # Log in to Docker Hub
# #       - name: Log in to Docker Hub
# #         run: echo "${{ secrets.PASSWORD_DOCKER }}" | docker login -u "${{ secrets.USER_NAME_DOCKER }}" --password-stdin

# #       # Build Docker image
# #       - name: Build Docker image
# #         run: docker build -t ${{ secrets.USER_NAME_DOCKER }}/llm:latest .

# #       # Push Docker image to Docker Hub
# #       - name: Push Docker image to Docker Hub
# #         run: docker push ${{ secrets.USER_NAME_DOCKER }}/llm:latest

# #       # Optional: Kubernetes deployment steps (commented out for now)
# #       # - name: Set up kubeconfig
# #       #   run: |
# #       #     mkdir -p $HOME/.kube
# #       #     echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

# #       # - name: Deploy to Kubernetes
# #       #   run: |
# #       #     kubectl set image deployment/myapp-deployment myapp=${{ secrets.USER_NAME_DOCKER }}/myapp:latest --namespace=default
# #       #     kubectl rollout status deployment/myapp-deployment --namespace=default
# name: Build and Deploy

# on:
#   push:
#     branches:
#       - main  # Change to your deployment branch if needed

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       # Set up Node.js 18.17.0
#       - name: Set up Node.js 18.17.0
#         uses: actions/setup-node@v4
#         with:
#           node-version: 18.17.0

#       # Set up Python 3.11 (if you have Python dependencies)
#       - name: Set up Python 3.11
#         uses: actions/setup-python@v5
#         with:
#           python-version: 3.11

#       # Install Python dependencies if any
#       - name: Install Python dependencies
#         run: |
#           python -m pip install --upgrade pip
#           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

#       # Check for index.html file
#       - name: Check for index.html
#         run: |
#           if [ ! -f ui/litellm-dashboard/index.html ]; then
#             echo "Error: index.html not found in ui/litellm-dashboard"
#             exit 1
#           fi

#       # Install Node.js dependencies and build the UI (React/Vue app)
#       - name: Install Node.js dependencies and build UI
#         working-directory: ui/litellm-dashboard
#         run: |
#           npm install
#           npm run build

#       # Log in to Docker Hub
#       - name: Log in to Docker Hub
#         run: echo "${{ secrets.PASSWORD_DOCKER }}" | docker login -u "${{ secrets.USER_NAME_DOCKER }}" --password-stdin

#       # Build Docker image
#       - name: Build Docker image
#         run: docker build -t ${{ secrets.USER_NAME_DOCKER }}/llm:latest .

#       # Push Docker image to Docker Hub
#       - name: Push Docker image to Docker Hub
#         run: docker push ${{ secrets.USER_NAME_DOCKER }}/llm:latest





name: Build and Deploy

on:
  push:
    branches:
      - main  # Change to your deployment branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js 18.17.0
      - name: Set up Node.js 18.17.0
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0

      # Install Node.js dependencies and build the UI
      - name: Conditionally run npm build
        working-directory: ui/litellm-dashboard
        run: |
          npm install
          if npm run | grep -q "build"; then
            echo "Running build..."
            npm run build
          else
            echo "No build script found. Skipping."
          fi

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.PASSEORD_DOCKER }}" | docker login -u "${{ secrets.USERNAME_DOCKER }}" --password-stdin

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.USERNAME_DOCKER }}/llm:latest ./ui/litellm-dashboard  # Ensure build context is inside the UI folder

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.USERNAME_DOCKER }}/llm:latest

